---
title: "Map_paris_Price"
author: "pol"
format: html
---
```{r}
library(dplyr)
library(sf)
library(ggplot2)
library(viridis) 
library(here)

```

```{r}
prix_iris_2020_25 <-readRDS(here("DATA_Processed" , "prix_iris_2020_25.rds"))

iris2020 <- st_read(
  here(
    "DATA_Raw",
    "CONTOURS-IRIS_2-1_SHP_LAMB93_FXX-2020",
    "CONTOURS-IRIS.shp"
  ),
  quiet = TRUE
) |>
  st_transform(2154) |>
  filter(substr(CODE_IRIS, 1, 2) == "75") |>
  select(CODE_IRIS, NOM_IRIS)
```


```{r}
prix_2020_25 <- prix_iris_2020_25 %>%
  group_by(CODE_IRIS) %>%
  summarise(
    prix_m2_med_2020_25 = median(prix_m2_med, na.rm = TRUE),
    n_annees            = n(),          
    .groups = "drop"
  ) %>%
  filter(n_annees >= 3)                 
```

```{r}

iris_price_2020_25 <- iris2020 %>%
  left_join(prix_2020_25, by = "CODE_IRIS")


iris_paris_2020_25 <- iris_price_2020_25 %>%
  filter(substr(CODE_IRIS, 1, 2) == "75")

```

```{r}
ggplot() +
  geom_sf(data = iris_paris_2020_25,
          aes(fill = prix_m2_med_2020_25),
          color = NA) +
  scale_fill_viridis(
    option   = "magma",
    direction = -1,
    na.value = "grey85",
    name     = "Prix/m² médian\n2020–2025"
  ) +
  theme_minimal() +
  labs(
    title    = "Prix au m² médian par IRIS – Paris (moyenne 2020–2025)",
    subtitle = "IRIS en gris : données DVF insuffisantes sur la période",
    caption  = "Source : DVF, Insee"
  ) +
  theme(
    panel.grid = element_blank(),
    axis.text  = element_blank(),
    axis.title = element_blank()
  )

```




```{r}
gentrif_indices <- readRDS(here("DATA_Processed", "gentrif_indices.rds"))
```




```{r}
iris2020 <- st_read(here(
    "DATA_Raw",
    "CONTOURS-IRIS_2-1_SHP_LAMB93_FXX-2020",
    "CONTOURS-IRIS.shp"
  ))

```


```{r}
iris_gentri <- iris2020 %>%
  filter(substr(CODE_IRIS, 1, 2) == "75") %>%  # seulement Paris
  left_join(gentrif_indices, by = c("CODE_IRIS" = "iris"))

```

```{r}
library(ggplot2)
library(viridis)

ggplot() +
  geom_sf(data = iris_gentri,
          aes(fill = gentrification_index_w),
          color = NA) +
  scale_fill_viridis(
    option    = "magma",
    direction = -1,
    na.value  = "grey85",
    name      = "Indice de gentrification"
  ) +
  theme_minimal() +
  labs(
    title    = "Indice de gentrification par IRIS – Paris",
    subtitle = "IRIS en gris : données manquantes",
    caption  = "Source : calculs propres à partir de DVF, Insee"
  ) +
  theme(
    panel.grid = element_blank(),
    axis.text  = element_blank(),
    axis.title = element_blank()
  )

```



