---
title: "Gentrification_Score"
author: "POL + MATEI"
format: html
---

```{r}
library(here)
dynamics_IRIS <- readRDS(here("DATA_Processed" , "dynamics_IRIS.rds"))
iris_overall <- readRDS(here("DATA_Processed" , "iris_overall.rds"))
index_rev <- readRDS(here("DATA_Processed" , "index_rev.rds"))
```

# Harmonizing iris across files
```{r}
index_price <- iris_overall %>%
  transmute(
    iris = CODE_IRIS,
    index_price
  )

index_pop <- dynamics_IRIS %>%
  transmute(
    iris = iris_2020,
    index_pop
  )

index_rev <- index_rev %>%
  transmute(
    iris,
    index_rev
  )

```

# Only keeping IRIS available in 3 
```{r}
gentrif_indices <- index_price %>%
  inner_join(index_pop, by = "iris") %>%
  inner_join(index_rev, by = "iris")

```

#Normalising results
```{r}

gentrif_indices <- gentrif_indices %>%
  mutate(
    z_price = as.numeric(scale(index_price)),
    z_pop   = as.numeric(scale(index_pop)),
    z_rev   = as.numeric(scale(index_rev))
  )

```

```{r}
cap <- function(x, k = 3) pmin(pmax(x, -k), k)

gentrif_indices <- gentrif_indices %>%
  mutate(
    z_price_c = cap(z_price, 3),
    z_pop_c   = cap(z_pop, 3),
    z_rev_c   = cap(z_rev, 3),
    gentrification_index_w =
      0.4 * z_price_c +
      0.3 * z_pop_c +
      0.3 * z_rev_c
  )
```

