---
title: "Cleaning BPE"
author: "Paul"
format: html
---

```{r}
library(sf)
library(dplyr)
library(vroom)
library(here)
library(tidyr)
```

# BPE for 2024
```{r}

iris2020 <- st_read(
  here(
    "DATA_Raw",
    "CONTOURS-IRIS_2-1_SHP_LAMB93_FXX-2020",
    "CONTOURS-IRIS.shp"
  ),
  quiet = TRUE
) |>
  st_transform(2154) |>
  filter(substr(CODE_IRIS, 1, 2) == "75") |>
  select(CODE_IRIS, NOM_IRIS)


bpe_keep <- c(
  "AN", "DEPCOM", "DEP", "REG", "LIBCOM",
  "DCIRIS", "LONGITUDE", "LATITUDE",
  "LAMBERT_X", "LAMBERT_Y", "QUALITE_XY", "QUALITE_GEOLOC", "EPSG",
  "DOM", "SDOM", "TYPEQU", "TYPE", "CATEGORIE"
)


BPE_Paris_2024 <- vroom(
  here("DATA_Raw", "BPE24.csv"),
  delim = ";",
  col_select = all_of(bpe_keep),
  show_col_types = FALSE
) |>
  filter(DEP == "75")

saveRDS(
  BPE_Paris_2024,
  here("DATA_Raw", "BPE_Paris_2024.rds")
)



BPE_Paris_2024_sf <- BPE_Paris_2024 |>
  filter(!is.na(LAMBERT_X), !is.na(LAMBERT_Y)) |>
  st_as_sf(
    coords = c("LAMBERT_X", "LAMBERT_Y"),
    crs    = 2154,
    remove = FALSE
  )

BPE_Paris_2024_iris <- st_join(
  BPE_Paris_2024_sf,
  iris2020,
  left = TRUE
) |>
  filter(!is.na(CODE_IRIS)) |>
  mutate(
    annee     = AN,
    iris_2020 = CODE_IRIS
  )

saveRDS(
  BPE_Paris_2024_iris,
  here("DATA_Processed", "BPE_Paris_2024_iris.rds")
)

```



#BPE for 2016
```{r}

BPE_2016 <- vroom(
  here("DATA_Raw", "BPE2016.csv"),
  delim = ";",
  show_col_types = FALSE
)


BPE_2016_clean <- BPE_2016 |>
  separate(
    `Geo Point`,
    into = c("latitude", "longitude"),
    sep = ",",
    convert = TRUE
  ) |>
  filter(!is.na(latitude), !is.na(longitude))

BPE_2016_paris <- BPE_2016_clean |>
  filter(dep == "75")  
saveRDS(
  BPE_2016_paris,
  here("DATA_Raw", "BPE_Paris_2016.rds")
)

BPE_2016_sf <- BPE_2016_clean |>
  st_as_sf(
    coords = c("longitude", "latitude"),
    crs = 4326,      # WGS84
    remove = FALSE
  ) |>
  st_transform(2154)


BPE_Paris_2016_iris <- st_join(
  BPE_2016_sf,
  iris2020,
  join = st_within,
  left = TRUE
) |>
  filter(!is.na(CODE_IRIS)) |>
  mutate(
    annee     = 2016,
    iris_2020 = CODE_IRIS
  )


saveRDS(
  BPE_Paris_2016_iris,
  here("DATA_Processed", "BPE_Paris_2016_iris.rds")
)


```



