---
title: "Cleaning FILOSFI FILES"
author: "Paul"
format: html
---

```{r}
library(here)
library(readxl)
library(janitor)
library(dplyr)
```

#2015
```{r}
D_rev2015 <- readxl::read_excel(here("DATA" , "BASE_TD_FILO_DEC_IRIS_2015.xls"), skip = 4)
names(D_rev2015)

D_rev2015_clean <- D_rev2015 %>%
  janitor::clean_names() %>%
  rename(
    iris = iris,
    iris_lib = libelle_de_l_iris,
    commune = commune_ou_arm,
    commune_lib = libelle_commune_ou_arm
  )

D_rev2015_clean <- D_rev2015_clean %>%
  mutate(iris = as.character(iris)) %>%
  filter(nchar(iris) == 9)

IDF_dep <- c("75","77","78","91","92","93","94","95")

D_rev2015_IDF <- D_rev2015_clean %>%
  mutate(dep = substr(iris, 1, 2)) %>%
  filter(dep %in% IDF_dep)


nrow(D_rev2015_IDF)
```

#2016
```{r}
here::i_am("Paris-Gentrification-ProjectDM.Rproj")
library(here)
library(readr)
D_rev2016 <- readxl::read_excel(here("DATA", "BASE_TD_FILO_DEC_IRIS_2016.xls"), skip = 4)

D_rev2016_clean <- D_rev2016 %>%
  janitor::clean_names() %>%
  rename(
    iris = iris,
    iris_lib = libelle_de_l_iris,
    commune = commune_ou_arm,
    commune_lib = libelle_commune_ou_arm
  )

D_rev2016_clean <- D_rev2016_clean %>%
  mutate(iris = as.character(iris)) %>%
  filter(nchar(iris) == 9)

IDF_dep <- c("75","77","78","91","92","93","94","95")

D_rev2016_IDF <- D_rev2016_clean %>%
  mutate(dep = substr(iris, 1, 2)) %>%
  filter(dep %in% IDF_dep)

nrow(D_rev2016_IDF)
```

#2018
```{r}
D_rev2018 <- readxl::read_excel(here("DATA" , "BASE_TD_FILO_DEC_IRIS_2018.xlsx"), skip = 4)
names(D_rev2018)


D_rev2018 <- D_rev2018 %>%
  janitor::clean_names() %>%
  rename(
    iris = iris,
    iris_lib = libelle_de_l_iris,
    commune = commune_ou_arm,
    commune_lib = libelle_commune_ou_arm
  )

D_rev2018 <- D_rev2018 %>%
  mutate(iris = as.character(iris)) %>%
  filter(nchar(iris) == 9)

IDF_dep <- c("75","77","78","91","92","93","94","95")

D_rev2018_IDF <- D_rev2018 %>%
  mutate(dep = substr(iris, 1, 2)) %>%
  filter(dep %in% IDF_dep)

nrow(D_rev2018_IDF)

```

#2020
```{r}
here::i_am("Paris-Gentrification-ProjectDM.Rproj")
library(here)
library(readr)
D_rev2020 <- readxl::read_excel(here("DATA", "BASE_TD_FILO_DEC_IRIS_2020.xlsx"), skip = 4)

D_rev2020 <- D_rev2020 %>%
  janitor::clean_names() %>%
  rename(
    iris = iris,
    iris_lib = libelle_de_l_iris,
    commune = commune_ou_arm,
    commune_lib = libelle_commune_ou_arm
  )

D_rev2020 <- D_rev2020 %>%
  mutate(iris = as.character(iris)) %>%
  filter(nchar(iris) == 9)

IDF_dep <- c("75","77","78","91","92","93","94","95")

D_rev2020_IDF <- D_rev2020 %>%
  mutate(dep = substr(iris, 1, 2)) %>%
  filter(dep %in% IDF_dep)

nrow(D_rev2020_IDF)
```

#2021
```{r}
D_rev2021 <- readxl::read_excel(here("DATA" , "BASE_TD_FILO_IRIS_2021_DEC.xlsx"), skip = 4)
names(D_rev2021)

D_rev2021 <- D_rev2021 %>%
  janitor::clean_names() %>%
  rename(
    iris = iris,
    iris_lib = libelle_de_l_iris,
    commune = commune_ou_arm,
    commune_lib = libelle_commune_ou_arm
  )

D_rev2021 <- D_rev2021 %>%
  mutate(iris = as.character(iris)) %>%
  filter(nchar(iris) == 9)

IDF_dep <- c("75","77","78","91","92","93","94","95")

D_rev2021_IDF <- D_rev2021 %>%
  mutate(dep = substr(iris, 1, 2)) %>%
  filter(dep %in% IDF_dep)

nrow(D_rev2021_IDF)
```

```{r}
library(dplyr)
library(janitor)

years <- c(2015, 2016, 2018, 2020, 2021)

dfs <- mget(paste0("D_rev", years, "_IDF")) 
names(dfs) <- years

filo_all <- purrr::imap_dfr(
  dfs,
  ~ .x %>%
    clean_names() %>%             
    mutate(annee = as.integer(.y))
)

glimpse(filo_all)
filo_all %>% count(annee)

```
```{r}
table_passage <- fread("DATA/table_passage_1999_2022.csv")



table_passage <- table_passage %>% clean_names()
names(table_passage)


```

```{r}

library(dplyr)

harmonize_to_iris2020 <- function(df, year) {
  
  df_clean <- df %>%
    clean_names() %>%        
    rename(iris_old = iris)  
  
  
  if (year %in% c(2020, 2021)) {
    
    res <- df_clean %>%
      mutate(
        iris_2020 = iris_old,   
        annee     = year
      )
    
  } else {
    
    col_year <- paste0("code_iris_", year)   
    
   
    passage_sub <- table_passage %>%
      select(code_iris_2020, !!col_year)
    
    res <- df_clean %>%
      left_join(
        passage_sub,
        by = c("iris_old" = col_year)   
      ) %>%
      mutate(
        iris_2020 = if_else(is.na(code_iris_2020), iris_old, code_iris_2020),
        annee     = year
      ) %>%
      select(-code_iris_2020)
  }
  
  return(res)
}


```

```{r}
filo2015 <- harmonize_to_iris2020(D_rev2015_IDF, 2015)
filo2016 <- harmonize_to_iris2020(D_rev2016_IDF, 2016)
filo2018 <- harmonize_to_iris2020(D_rev2018_IDF, 2018)
filo2020 <- harmonize_to_iris2020(D_rev2020_IDF, 2020)
filo2021 <- harmonize_to_iris2020(D_rev2021_IDF, 2021)

filo_all2 <- dplyr::bind_rows(filo2015, filo2016, filo2018, filo2020, filo2021)

# Vérif :
filo_all %>% count(annee)
length(unique(filo_all$iris_2020))


```

