---
title: "Final analysis"
author: "Paul JOAHNY and Matei Vasile"
format: html
---

```{r}
library(here)
library(dplyr)
library(ggplot2)
library(here)
library(sf)
BPE_final_clean <- readRDS(here("DATA_Processed" , "BPE_final_clean.rds"))
gentrif_indices <- readRDS(here("DATA_Processed", "gentrif_indices.rds")) 

```


```{r}

quartiles <- gentrif_indices %>%
  mutate(score_quartile = ntile(gentrification_score, 4)) %>%
  select(iris, score_quartile)

data_combined <- BPE_final_clean %>%
  left_join(quartiles, by = "iris")
data_combined <- data_combined %>%
  left_join(
    gentrif_indices %>%
      select(iris, gentrification_score),
    by = "iris"
  )

data_combined <- data_combined %>%
  st_drop_geometry()


saveRDS(data_combined , here("DATA_Processed" , "data_combined.rds"))
```

```{r}

data_combined <- data_combined %>%
  mutate(
    categorie = case_when(
      str_detect(type_clean, regex("restaurant", ignore_case = TRUE)) ~ "Restauration",
      type_clean %in% c(
        "boulangerie-patisserie", "boucherie charcuterie", "poissonnerie", 
        "epicerie", "commerce specialise en fruits et legumes", "produits surgeles", 
        "superette", "supermarche", "supermarche et magasin multi-commerce", 
        "hypermarche et grand magasin", "autres commerces alimentaires"
      ) ~ "Proximity",
      type_clean %in% c(
        "coiffure", "institut de beaute–onglerie", "parfumerie–cosmetique", 
        "pressing–laverie automatique", "blanchisserie–teinturerie", 
        "agence de travail temporaire", "agence immobiliere", "veterinaire"
      ) ~ "Services",
      type_clean %in% c(
        "librairie–papeterie–journaux", "magasin de vetements", "magasin de chaussures",
        "magasin d'optique", "horlogerie–bijouterie", "maroquinerie et articles de voyage",
        "magasin de meubles", "magasin d'equipements du foyer",
        "magasin d'electromenager et de mat. audio–video",
        "magasin electromenager, materiel audio video informatique",
        "magasin de materiels de telecommunication",
        "commerce de jeux et jouets", "magasin d'art. de sports et de loisirs",
        "magasin d'articles de sports et de loisirs", "commerce de biens d'occasion",
        "commerce de tissus et mercerie", "droguerie quincaillerie bricolage",
        "grande surface de bricolage", "magasin de revetements murs et sols",
        "magasin de materiel medical et orthopedique", "commerce de boissons"
      ) ~ "Specialised Businesses",
      TRUE ~ "Other"
    )
  )


```

```{r}
df_quartiles <- data_combined %>%
  filter(!is.na(score_quartile)) %>%   
  group_by(score_quartile, year, categorie) %>%
  summarise(nb_commerces = sum(nb, na.rm = TRUE), .groups = "drop") %>%
  group_by(score_quartile, year) %>%
  mutate(part = nb_commerces / sum(nb_commerces))

```




```{r}
ggplot(df_quartiles, aes(x = factor(year), y = part, fill = categorie)) +
  geom_col() +
  scale_y_continuous(labels = scales::percent) +
  facet_wrap(~ score_quartile, nrow = 1, labeller = labeller(score_quartile = 
                                                               c("1" = "Q1 Low gentrification",
                                                                 "2" = "Quartile 2",
                                                                 "3" = "Quartile 3",
                                                                 "4" = "Q4 Strong gentrification"))) +
  labs(
    x = "Year",
    y = "Share of Businesses",
    fill = "Category",
    title = "Commercial composition according to the quartile and year "
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


```


```{r}
library(ggplot2)

# Filtrer uniquement la catégorie Restauration
df_rest_quartiles <- df_quartiles %>%
  filter(categorie == "Restauration")

# Graphique
ggplot(df_rest_quartiles, aes(x = year, y = part, color = factor(score_quartile), group = score_quartile)) +
  geom_line(size = 1.2) +
  geom_point(size = 3) +
  scale_color_brewer(palette = "Set1", name = "Quartile de gentrification") +
  labs(
    title = "Part des restaurants selon les quartiles de gentrification",
    x = "Année",
    y = "Part des restaurants"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "top",
    plot.title = element_text(face = "bold", hjust = 0.5)
  )

```

```{r}
tab_chi2 <- data_combined %>%
  group_by(score_quartile, categorie) %>%
  summarise(nb = sum(nb, na.rm = TRUE), .groups = "drop") %>%
  tidyr::pivot_wider(
    names_from = categorie,
    values_from = nb,
    values_fill = 0
  )

chisq.test(as.matrix(tab_chi2[,-1]))

```
```{r}
library(rcompanion)

cramerV(as.matrix(tab_chi2[, -1]))

```


```{r}
reg_simple <- lm(
  part ~ score_quartile,
  data = df_quartiles
)

summary(reg_simple)

```
```{r}
reg_inter <- lm(
  part ~ score_quartile * categorie,
  data = df_quartiles
)

summary(reg_inter)

```

