---
title: "Index_Creation"
format: html
author: "Matei Vasile"
---

```{r}
library(data.table)
library(dplyr)
library(purrr)
library(broom)
library(scales)
library(here)
library(tidyr)
```


#DVF index
```{r}
file <- here("DATA_Processed", "prix_iris_2014_25.rds")

df <- readRDS(file)

yoy <- df %>%
  arrange(CODE_IRIS, annee) %>%
  group_by(CODE_IRIS) %>%
  mutate(growth = prix_m2_med / lag(prix_m2_med) - 1) %>%
  ungroup() %>%
  filter(!is.na(growth))

bench <- yoy %>%
  group_by(annee) %>%
  summarise(avg_growth = mean(growth, na.rm = TRUE), .groups = "drop")

rel <- yoy %>%
  left_join(bench, by = "annee") %>%
  mutate(rel_growth = growth - avg_growth)

iris_overall <- rel %>%
  group_by(CODE_IRIS) %>%
  summarise(
    mean_rel_growth = mean(rel_growth, na.rm = TRUE),
    n_years = n(),
    index_price = (1 + mean_rel_growth),
    .groups = "drop"
  ) %>%
  filter(n_years >= 5) %>%
  arrange(desc(mean_rel_growth))
```
```{r}
saveRDS(iris_overall, here("DATA_Processed", "iris_overall.rds"))
```


#Population index

#Creating new variables 
```{r}
JOB_all <- readRDS(here("DATA_Processed", "JOB_all.rds"))

JOB_all_clean <- JOB_all |>
  filter(actocc1564 > 0, act1564 > 0) |>
  mutate(
    share_csp_sup   = (cadres_1564 + prof_inter_1564) / actocc1564,  
    share_populaire = (employes_1564 + ouvriers_1564) / actocc1564,
    share_chom      = chom1564 / act1564
  )
```

#New base calculating slopes
```{r}
JOB_gentrification <- JOB_all_clean |>
  select(
    iris_2020,
    annee,
    share_csp_sup,
    share_populaire,
    share_chom
  )

get_slope <- function(df, var) {
  lm(as.formula(paste(var, "~ annee")), data = df) |>
    broom::tidy() |>
    filter(term == "annee") |>
    pull(estimate)
}
```

```{r}
dynamics_IRIS <- JOB_gentrification |>
  group_by(iris_2020) |>
  filter(n() >= 4) |>
  nest() |>
  mutate(
    slope_CSP_plus = map_dbl(data, ~ get_slope(.x, "share_csp_sup")),
    slope_CSP_pop  = map_dbl(data, ~ get_slope(.x, "share_populaire")),
    slope_chom     = map_dbl(data, ~ get_slope(.x, "share_chom"))
  ) |>
  select(-data) |>
  ungroup()

dynamics_IRIS <- dynamics_IRIS |>
  mutate(
    Z_CSP_plus = as.numeric(scale(slope_CSP_plus)),
    Z_CSP_pop  = as.numeric(scale(slope_CSP_pop)),
    Z_chom     = as.numeric(scale(slope_chom))
  )


dynamics_IRIS <- dynamics_IRIS |>
  mutate(
    index_pop = Z_CSP_plus - Z_CSP_pop - Z_chom
  ) |>
  arrange(desc(index_pop)) 

head(dynamics_IRIS)
```
```{r}
saveRDS(dynamics_IRIS, here("DATA_Processed", "dynamics_IRIS.rds"))
```


#Revenue Index

```{r}
df_raw <- readRDS(
  here("DATA_Processed", "filo_final.rds")
)
```

```{r}
df_index <- df_raw %>%
  transmute(iris_lib, commune, commune_lib, poverty_share = taux_de_bas_revenus_declares_au_seuil_de_60_percent_percent, mediane, indice_de_gini, x1er_decile, annee, iris = iris_2020, dep)

df_new <- df_index %>%
  mutate(mediane = as.numeric(mediane), poverty_share = as.numeric(poverty_share))
```

```{r}
df_income <- df_new %>%
  group_by(iris, annee) %>%
  summarise(
    mediane = median(mediane, na.rm = TRUE),
    .groups = "drop"
  )

income_yoy <- df_income %>%
  arrange(iris, annee) %>%
  group_by(iris) %>%
  mutate(
    year_gap = annee - lag(annee),
    income_growth = (mediane / lag(mediane))^(1 / year_gap) - 1
  ) %>%
  ungroup() %>%
  filter(!is.na(income_growth))

income_bench <- income_yoy %>%
  group_by(annee) %>%
  summarise(
    avg_income_growth = mean(income_growth, na.rm = TRUE),
    .groups = "drop"
  )

income_overall <- income_yoy %>%
  left_join(income_bench, by = "annee") %>%
  mutate(
    rel_income_growth = income_growth - avg_income_growth
  ) %>%
  arrange(iris, annee) %>%
  group_by(iris) %>%
  summarise(
    income_index_score_1 = last(cumprod(1 + rel_income_growth)),
    mean_rel_income_growth = mean(rel_income_growth, na.rm = TRUE),
    n_years = n_distinct(annee),
    .groups = "drop"
  ) %>%
  filter(n_years >= 2) %>%
  arrange(desc(income_index_score_1))
```

```{r}
df_poverty <- df_new %>%
  mutate(poverty_share = readr::parse_number(as.character(poverty_share))) %>%
  group_by(iris, annee) %>%
  summarise(
    poverty_share = median(poverty_share, na.rm = TRUE),
    .groups = "drop"
  )

poverty_ranked <- df_poverty %>%
  filter(!is.na(poverty_share)) %>%              
  group_by(annee) %>%
  mutate(
    poverty_rank = percent_rank(poverty_share),
    poverty_rank_good = 1 - poverty_rank
  ) %>%
  ungroup()

poverty_overall <- poverty_ranked %>%
  arrange(iris, annee) %>%
  group_by(iris) %>%
  summarise(
    n_years = n_distinct(annee),
    start_rank_good = first(poverty_rank_good),  
    end_rank_good   = last(poverty_rank_good),
    poverty_rank_change = end_rank_good - start_rank_good,
    mean_rank_good = mean(poverty_rank_good, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  filter(n_years >= 2) %>%
  arrange(desc(poverty_rank_change))
```

```{r}
index_rev <- income_overall %>%
  select(iris, income_index_score_1) %>%
  inner_join(
    poverty_overall %>% select(iris, poverty_rank_change),
    by = "iris"
  ) %>%
  mutate(
    z_income  = as.numeric(scale(income_index_score_1)),
    z_poverty = as.numeric(scale(poverty_rank_change)),
    index_rev = z_income + z_poverty   
  ) %>%
  arrange(desc(index_rev))
```
```{r}
saveRDS(index_rev, here("DATA_Processed", "index_rev.rds"))
```

